name: stardist-cpu
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scikit-image
  - tifffile
  - tqdm
  - ipywidgets
  - iprogress
  - pyyaml
  - pydantic=1.10.10
  - jupyter
  - h5py
  - matplotlib
  - numpy=1.25.2
  - werkzeug=3.0.0
  - termcolor=2.3.0
  - requests-oauthlib=1.3.1
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - absl-py=2.0.0
  - astunparse=1.6.3
  - cachetools=5.3.1
  - python-flatbuffers=23.5.26
  - flatbuffers=23.5.26
  - markdown=3.5
  - numba::numba=0.58.0
  - opt-einsum=3.3.0
  - rsa=4.9
  - pre-commit
  - questionary
  - sphinx
  - furo
  - myst-parser
  - sphinx-inline-tabs
  - sphinx-copybutton
  - pip
  - pip:
      - tensorflow
      - stardist
